apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ztncui.fullname" . }}
  labels:
    {{- include "ztncui.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "ztncui.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "ztncui.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "ztncui.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
      - name: verify-and-change-pass
        image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        command: ['sh','-c','ls -l /app/src/etc/passwd || cp /app/etc/default.passwd /app/src/etc/passwd']
        volumeMounts:
        - name: zerotier-one 
          mountPath: /app/src/etc/
          subPath: passwd
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          env:
          - name: HTTP_ALL_INTERFACES
            value: "true"
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          volumeMounts:
          - mountPath: /app/src/etc/
            name: zerotier-one
            subPath: passwd
          - mountPath: /var/lib/zerotier-one/
            name: zerotier-one
            subPath: zerotier-one
 
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
      - name: zerotier-one
        {{- if .Values.persistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ .Values.persistence.existingClaim | default (include "ztncui.fullname" .) }}
        {{- else }}
        emptyDir: {}
        {{- end }}
 
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
