apiVersion: v1
kind: Service
metadata:
  name: {{ include "ztncui.fullname" . }}
  labels:
    {{- include "ztncui.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3000 
      protocol: TCP
      name: http
  selector:
    {{- include "ztncui.selectorLabels" . | nindent 4 }}
