{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ztncui.serviceAccountName" . }}
  labels:
{{ include "ztncui.labels" . | nindent 4 }}
{{- end -}}
